SELECT CITY, LENGTH(CITY) 
FROM (SELECT CITY, LENGTH(CITY) 
FROM STATION 
ORDER BY LENGTH(CITY), CITY )
where rownum = 1; 

SELECT CITY, LENGTH(CITY) 
FROM ( SELECT CITY, LENGTH(CITY) 
FROM STATION 
ORDER BY LENGTH(CITY) desc, CITY )
where rownum = 1; 